# Generated by Django 3.2 on 2022-03-31 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_cooupon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cooupon',
            new_name='Coupon',
        ),
    ]
