# Generated by Django 3.2 on 2022-03-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_abv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='abv',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
    ]
