# Generated by Django 3.2 on 2022-04-02 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_rating',
            new_name='rating',
        ),
    ]
