# Generated by Django 3.2 on 2022-05-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_product_rating_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='status',
        ),
    ]
